### ISSUE TITLE
Items on Bloch Sphere screen can shift

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/quantum-measurement#104]
**Test device**
MacBook Air (M1 chip)

**Operating System**
15.3

**Browser**
Safari 18.3

**Problem description**
For https://github.com/phetsims/qa/issues/1207, on the Bloch Sphere screen, moving the Polar slider to min/max values causes the panel and `blochSphereNode` to shift upward. 

**Steps to reproduce**
1. On the Bloch Sphere screen, move the Polar Angle slider to 0 and pi

**Visuals**

https://github.com/user-attachments/assets/d2fc6bda-3899-4609-983b-71a6d1ac4a32

**Comment by AgustinVallejo** [comment]
Hot potato back to you @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment]
🥔 I see a slight left-right shift. 
It happens in all of the text, but this video only shows the text in the panel:

https://github.com/user-attachments/assets/d0121fa3-e559-462a-b012-706f33e692f0

Passing the torch to you.....

**Comment by Nancy-Salpepi** [comment]
There is also shifting on the right side when I press the Observe/Reprepare button.

https://github.com/user-attachments/assets/c2aa2598-bf98-48ee-b774-0881c260ee3d

**Comment by Nancy-Salpepi** [comment]
Wondering if the default positions of the systemUnderTestNode and Magnetic Field should be a bit higher to begin with? Like where the systemUnderTestNode is in this screenshot:

<img width="324" alt="Image" src="https://github.com/user-attachments/assets/84a7909e-de34-451d-86cb-93b873616823" />

That way, there would be no shifting?

After Pressing Start, changing the magnetic field causes the systemUnderTestNode to move up and down:

https://github.com/user-attachments/assets/ec3961d1-94e3-48e3-93c0-22bd9d3b2049

**Comment by Nancy-Salpepi** [comment]
On main, after your first commit, the atoms and title shift when the magnet field is set to zero.

<img width="325" alt="Image" src="https://github.com/user-attachments/assets/bfff2708-5c83-414a-bd1c-daa32d8acf8a" /><img width="325" alt="Image" src="https://github.com/user-attachments/assets/c914ba22-4ec8-4e43-bf9e-05c391aa2fd8" />

**Comment by AgustinVallejo** [comment]
I think these two new items (vertical jumping on observation and atoms left aligning) should now be fixed, although for the first thing I didn't do anything really, so please check. Inelastic bounce back to you @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment]
-I still see a slight left/right shift on the left side (keep your eye on the gray panel as you move the Polar Angle slider back and forth)
-Wondering why checking Enable Magnetic Field causes a shift in the histrograms, eraser button and measurement controls? Should the gray area just get longer but everything else stays in place? Is that a case where the min width needs to be increased?

https://github.com/user-attachments/assets/08eea75d-848a-4586-ace2-d39f8ee8518d

-the atoms/title looks good now!

**Comment by AgustinVallejo** [comment]
I think this is now fixed for good. Tennis serving back to @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment]
Right side looks great. Left side still has the tiny shift when moving the Polar Angle slider between min and max. 
So....."Europe"....get it? 😂

**Comment by AgustinVallejo** [comment]
Hopefully the above if the one fix to fix them all now. Casting it back to youu @Nancy-Salpepi !!!

**Comment by Nancy-Salpepi** [comment]
love the LotR reference there!

It is fixed!!!!!!!!!!!!!!!!!!!!!!!!
